# .air.toml

# The log level: debug, info, warn, error
log_level = "debug"

# Which binary to run (output binary name)
bin = "tmp/main"

# The main package to watch (entrypoint relative to root)
main = "cmd/main.go"

# Command to run after a rebuild
cmd = "go build -o tmp/main cmd/main.go"

# Extensions to watch for live reload
include_ext = ["go", "tpl", "tmpl", "html"]

# Directories to ignore from watching
exclude_dir = ["assets", "tmp", "vendor", "docs"]

# Delay before restarting after a change (in ms)
delay = 100
